##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.14.1] date: [Sat Apr 09 21:59:10 CDT 2022] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = MidiMatrix


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = 


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/usart.c \
Core/Src/stm32f4xx_it.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_utils.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_exti.c \
Core/Src/syscalls.c \
Core/Src/system_stm32f4xx.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f401xe.s

# D sources

D_SOURCES =	\
	source/main.d		\
	source/io.d			\
	source/midi.d		\
	source/ringbuf.d	\


# Generate D modules
DSTEP_MODULES= \
	Drivers.STM32F4xx_HAL_Driver.Inc.stm32f4xx_ll_usart				\
	Drivers.STM32F4xx_HAL_Driver.Inc.stm32f4xx_ll_gpio				\
    Drivers.CMSIS.Device.ST.STM32F4xx.Include.stm32f4xx     		\
    Drivers.CMSIS.Device.ST.STM32F4xx.Include.stm32f401xe    		\
    Drivers.CMSIS.Device.ST.STM32F4xx.Include.system_stm32f4xx 		\
    Core.Inc.main                   \
    Core.Inc.stm32_assert           \
    Core.Inc.stm32f4xx_it           \
    Core.Inc.gpio                   \
    Core.Inc.usart                  \

# Files which need patched (eg. to remove invalid UTF-8)
PATCHED_FILES=  \
    Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h   	\
    Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f401xe.h   	\

# List of headers with inline functions to implement
INLINE_IMPL_HEADERS = 	\
	Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_usart.h \
	Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_ll_gpio.h \


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_FULL_ASSERT=1U \
-DHSE_VALUE=8000000 \
-DHSE_STARTUP_TIMEOUT=100 \
-DLSE_STARTUP_TIMEOUT=5000 \
-DLSE_VALUE=32768 \
-DVDD_VALUE=3300 \
-DPREFETCH_ENABLE=1 \
-DEXTERNAL_CLOCK_VALUE=12288000 \
-DHSI_VALUE=16000000 \
-DLSI_VALUE=32000 \
-DINSTRUCTION_CACHE_ENABLE=1 \
-DDATA_CACHE_ENABLE=1 \
-DSTM32F401xE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/CMSIS/Include \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include

# Warning flags
WFLAGS=-Werror -Wall -Wextra -pedantic -Wno-unused-parameter

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections $(WFLAGS)

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F401RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################

# Include Makefile.dlang as it finishes everything up and contains the rules
-include Makefile.dlang

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
